#!/usr/bin/env bash
# generate-credentials.sh — generate a ~/.vsphere/credentials template for per-component credentials.
#
# Usage:
#   bash generate-credentials.sh
#
# Environment variables:
#   VSPHERE_HOSTNAMES       comma-separated vCenter FQDNs (e.g. "vc1.example.com,vc2.example.com")
#   MACHINEAPI_USERNAME     username for the Machine API service account
#   CSIDRIVER_USERNAME      username for the CSI driver service account
#   CLOUDCONTROLLER_USERNAME username for the Cloud Controller Manager service account
#   DIAGNOSTICS_USERNAME    username for the vSphere Problem Detector service account
#
# Output:
#   ~/.vsphere/credentials with permissions 0600 (directory 0700).

set -euo pipefail

: "${VSPHERE_HOSTNAMES:?VSPHERE_HOSTNAMES must be set (comma-separated list of vCenter FQDNs)}"

MACHINEAPI_USERNAME="${MACHINEAPI_USERNAME:-svc-machineapi@vsphere.local}"
CSIDRIVER_USERNAME="${CSIDRIVER_USERNAME:-svc-csidriver@vsphere.local}"
CLOUDCONTROLLER_USERNAME="${CLOUDCONTROLLER_USERNAME:-svc-cloudcontroller@vsphere.local}"
DIAGNOSTICS_USERNAME="${DIAGNOSTICS_USERNAME:-svc-diagnostics@vsphere.local}"

OUTPUT_DIR="${HOME}/.vsphere"
OUTPUT_FILE="${OUTPUT_DIR}/credentials"

mkdir -p "${OUTPUT_DIR}"
chmod 0700 "${OUTPUT_DIR}"

IFS=',' read -ra VCENTER_LIST <<< "${VSPHERE_HOSTNAMES}"
if [[ ${#VCENTER_LIST[@]} -eq 0 || -z "${VCENTER_LIST[0]}" ]]; then
  echo "ERROR: VSPHERE_HOSTNAMES is empty; at least one vCenter FQDN is required" >&2
  exit 1
fi

{
  echo "# ~/.vsphere/credentials — per-component vCenter credential file"
  echo "# Generated by generate-credentials.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "# Fill in the password fields before use."
  echo ""

  for VCENTER in "${VCENTER_LIST[@]}"; do
    VCENTER="$(echo "${VCENTER}" | xargs)"  # trim whitespace
    if [[ -z "${VCENTER}" ]]; then
      continue
    fi

    cat <<EOF
${VCENTER}:
  machineAPI:
    username: ${MACHINEAPI_USERNAME}
    password: ""
  csiDriver:
    username: ${CSIDRIVER_USERNAME}
    password: ""
  cloudController:
    username: ${CLOUDCONTROLLER_USERNAME}
    password: ""
  diagnostics:
    username: ${DIAGNOSTICS_USERNAME}
    password: ""
EOF
  done
} > "${OUTPUT_FILE}"

chmod 0600 "${OUTPUT_FILE}"

echo "Credentials template written to: ${OUTPUT_FILE}"
echo "IMPORTANT: fill in the password fields before running the installer."
