package manifests

import (
	"context"
	"fmt"
	"path/filepath"

	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"sigs.k8s.io/yaml"

	"github.com/openshift/installer/pkg/asset"
	"github.com/openshift/installer/pkg/asset/installconfig"
	vspheretypes "github.com/openshift/installer/pkg/types/vsphere"
)

const (
	// Component secret names
	vsphereInstallerCredsSecretName       = "vsphere-installer-creds"
	vsphereMachineAPICredsSecretName      = "vsphere-machine-api-creds"
	vsphereStorageCredsSecretName         = "vsphere-storage-creds"
	vsphereCloudControllerCredsSecretName = "vsphere-cloud-controller-creds"
	vsphereDiagnosticsCredsSecretName     = "vsphere-diagnostics-creds"
	vsphereCloudCredentialsSecretName     = "vsphere-cloud-credentials"

	// Namespace for all component secrets
	componentSecretsNamespace = "kube-system"
)

var (
	vsphereComponentSecretsFileNames = map[string]string{
		vsphereInstallerCredsSecretName:       filepath.Join(manifestDir, "vsphere-installer-creds.yaml"),
		vsphereMachineAPICredsSecretName:      filepath.Join(manifestDir, "vsphere-machine-api-creds.yaml"),
		vsphereStorageCredsSecretName:         filepath.Join(manifestDir, "vsphere-storage-creds.yaml"),
		vsphereCloudControllerCredsSecretName: filepath.Join(manifestDir, "vsphere-cloud-controller-creds.yaml"),
		vsphereDiagnosticsCredsSecretName:     filepath.Join(manifestDir, "vsphere-diagnostics-creds.yaml"),
		vsphereCloudCredentialsSecretName:     filepath.Join(manifestDir, "vsphere-cloud-credentials.yaml"),
	}
)

// VSphereComponentSecrets generates component-specific credential secrets for vSphere.
type VSphereComponentSecrets struct {
	// Secrets holds the component secret manifests
	Secrets map[string]*corev1.Secret
	files   []*asset.File
}

var _ asset.WritableAsset = (*VSphereComponentSecrets)(nil)

// Name returns the human-friendly name of the asset.
func (s *VSphereComponentSecrets) Name() string {
	return "vSphere Component Secrets"
}

// Dependencies returns all dependencies for the asset.
func (s *VSphereComponentSecrets) Dependencies() []asset.Asset {
	return []asset.Asset{
		&installconfig.InstallConfig{},
	}
}

// Generate generates the vSphere component secrets.
func (s *VSphereComponentSecrets) Generate(_ context.Context, dependencies asset.Parents) error {
	installConfig := &installconfig.InstallConfig{}
	dependencies.Get(installConfig)

	// Only generate secrets for vSphere platform
	if installConfig.Config.Platform.VSphere == nil {
		return nil
	}

	platform := installConfig.Config.Platform.VSphere

	// Check if component credentials are configured
	if !hasComponentCredentials(platform) {
		return nil
	}

	s.Secrets = make(map[string]*corev1.Secret)

	// Generate component secrets
	componentCreds := map[string]*vspheretypes.ComponentCredentials{
		vsphereInstallerCredsSecretName:       platform.ComponentCredentials.Installer,
		vsphereMachineAPICredsSecretName:      platform.ComponentCredentials.MachineAPI,
		vsphereStorageCredsSecretName:         platform.ComponentCredentials.Storage,
		vsphereCloudControllerCredsSecretName: platform.ComponentCredentials.CloudController,
		vsphereDiagnosticsCredsSecretName:     platform.ComponentCredentials.Diagnostics,
	}

	// Create component-specific secrets
	for secretName, creds := range componentCreds {
		if creds == nil {
			continue
		}

		secret, err := createComponentSecret(secretName, creds, platform.VCenters)
		if err != nil {
			return fmt.Errorf("failed to create secret %s: %w", secretName, err)
		}
		s.Secrets[secretName] = secret
	}

	// Create operational credentials secret (vsphere-cloud-credentials)
	// Use installer credentials as operational credentials (may be refined in future)
	if platform.ComponentCredentials.Installer != nil {
		secret, err := createComponentSecret(
			vsphereCloudCredentialsSecretName,
			platform.ComponentCredentials.Installer,
			platform.VCenters,
		)
		if err != nil {
			return fmt.Errorf("failed to create vsphere-cloud-credentials secret: %w", err)
		}
		s.Secrets[vsphereCloudCredentialsSecretName] = secret
	}

	// Generate YAML files for each secret
	s.files = make([]*asset.File, 0, len(s.Secrets))
	for secretName, secret := range s.Secrets {
		data, err := yaml.Marshal(secret)
		if err != nil {
			return fmt.Errorf("failed to marshal secret %s: %w", secretName, err)
		}

		filename := vsphereComponentSecretsFileNames[secretName]
		s.files = append(s.files, &asset.File{
			Filename: filename,
			Data:     data,
		})
	}

	return nil
}

// Files returns the files generated by the asset.
func (s *VSphereComponentSecrets) Files() []*asset.File {
	return s.files
}

// Load loads the asset from disk (not implemented for this asset).
func (s *VSphereComponentSecrets) Load(f asset.FileFetcher) (bool, error) {
	return false, nil
}

// hasComponentCredentials checks if any component credentials are configured.
func hasComponentCredentials(platform *vspheretypes.Platform) bool {
	if platform.ComponentCredentials == nil {
		return false
	}

	creds := platform.ComponentCredentials
	return creds.Installer != nil ||
		creds.MachineAPI != nil ||
		creds.Storage != nil ||
		creds.CloudController != nil ||
		creds.Diagnostics != nil
}

// createComponentSecret creates a Kubernetes Secret for a component with multi-vCenter credentials.
func createComponentSecret(
	secretName string,
	creds *vspheretypes.ComponentCredentials,
	vcenters []vspheretypes.VCenter,
) (*corev1.Secret, error) {
	secretData := make(map[string]string)

	// Build multi-vCenter credential map
	for _, vcenter := range vcenters {
		// Get credentials for this vCenter
		username, password, err := getCredentialsForVCenter(creds, vcenter.Server)
		if err != nil {
			return nil, fmt.Errorf("failed to get credentials for vCenter %s: %w", vcenter.Server, err)
		}

		// Add credentials with vCenter FQDN as key prefix
		usernameKey := fmt.Sprintf("%s.username", vcenter.Server)
		passwordKey := fmt.Sprintf("%s.password", vcenter.Server)
		secretData[usernameKey] = username
		secretData[passwordKey] = password
	}

	secret := &corev1.Secret{
		TypeMeta: metav1.TypeMeta{
			APIVersion: corev1.SchemeGroupVersion.String(),
			Kind:       "Secret",
		},
		ObjectMeta: metav1.ObjectMeta{
			Namespace: componentSecretsNamespace,
			Name:      secretName,
		},
		Type:       corev1.SecretTypeOpaque,
		StringData: secretData,
	}

	return secret, nil
}

// getCredentialsForVCenter extracts username and password for a specific vCenter.
func getCredentialsForVCenter(creds *vspheretypes.ComponentCredentials, vcenterFQDN string) (string, string, error) {
	if creds == nil {
		return "", "", fmt.Errorf("component credentials are nil")
	}

	// Direct credentials (single-vCenter or default)
	if creds.Username != "" && creds.Password != "" {
		return creds.Username, creds.Password, nil
	}

	// Multi-vCenter credentials from secretRef
	if creds.SecretRef != nil && len(creds.SecretRef.VCenters) > 0 {
		for _, vc := range creds.SecretRef.VCenters {
			if vc.Server == vcenterFQDN {
				return vc.Username, vc.Password, nil
			}
		}
		return "", "", fmt.Errorf("credentials not found for vCenter %s", vcenterFQDN)
	}

	return "", "", fmt.Errorf("no credentials configured")
}
